"""empty message

Revision ID: 432c62a79890
Revises: deecaec4b4fe
Create Date: 2023-08-19 09:10:57.240411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "432c62a79890"
down_revision = "deecaec4b4fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "task",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=5000),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "task",
            existing_type=sa.String(length=5000),
            type_=sa.VARCHAR(length=200),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
