"""check status

Revision ID: 64068c3572e1
Revises: 7bb6b948e468
Create Date: 2023-12-01 12:21:51.610080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64068c3572e1"
down_revision: Union[str, None] = "7bb6b948e468"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "time_sheet",
        "location",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        nullable=True,
        existing_server_default=sa.text("'In Person'::character varying"),
    )
    op.create_index(
        op.f("ix_time_sheet_project_id"),
        "time_sheet",
        ["project_id"],
        unique=False,
    )
    op.alter_column(
        "user",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.drop_constraint("user_slack_id_key", "user", type_="unique")
    op.create_index(
        op.f("ix_user_project_id"),
        "user",
        ["project_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_user_slack_id"),
        "user",
        ["slack_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_slack_id"), table_name="user")
    op.drop_index(op.f("ix_user_project_id"), table_name="user")
    op.create_unique_constraint("user_slack_id_key", "user", ["slack_id"])
    op.alter_column("user", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_time_sheet_project_id"), table_name="time_sheet")
    op.alter_column(
        "time_sheet",
        "location",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'In Person'::character varying"),
    )
    # ### end Alembic commands ###
