""" added the reminder table

Revision ID: 6f936f276039
Revises: b2bd3ceee620
Create Date: 2024-01-07 23:54:25.399384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f936f276039"
down_revision: Union[str, None] = "b2bd3ceee620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reminder_time", sa.Time(), nullable=False),
        sa.Column("notification_type", sa.String(length=100), nullable=False),
        sa.Column("slack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["slack_id"],
            ["user.slack_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminder_id"), "reminder", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminder_id"), table_name="reminder")
    op.drop_table("reminder")
    # ### end Alembic commands ###
