"""empty message

Revision ID: 7bb6b948e468
Revises: 432c62a79890
Create Date: 2023-08-19 14:58:47.071558

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "7bb6b948e468"
down_revision = "432c62a79890"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["slack_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
