"""added telegram_id row

Revision ID: bd8e11bbb7b8
Revises: 6f936f276039
Create Date: 2024-02-02 18:57:23.930692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8e11bbb7b8'
down_revision: Union[str, None] = '6f936f276039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###
