version: "3.8"

services:
  backend:
    container_name: slack-bot-backend
    environment:
      - ENVIRONMENT: ${ENVIRONMENT}
      - TEST_DATABASE_URI: ${TEST_DATABASE_URI}
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: slack-bot-database
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5457:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=slack-bot

volumes:
  postgres_data:
