name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      TEST_DATABASE_URI: ${{ vars.TEST_DATABASE_URI }}

    steps:
      - uses: actions/checkout@v2

      - name: check secret
        shell: bash
        run: echo "the environment is $ENVIRONMENT"

      # - name: Build the stack
      #   working-directory: fast_api_backend
      #   run: docker-compose up -d

      # - name: Run tests
      #   working-directory: fast_api_backend
      #   run: docker-compose exec -T backend pytest -p no:warnings -s
