name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      TEST_DATABASE_URI: ${{ vars.TEST_DATABASE_URI }}
      OPENAI_API_URL: ${{ secrets.OPENAI_API_URL }}
      APP_TOKEN: ${{ vars.APP_TOKEN }}
      Telegram_BOT_TOKEN: ${{ vars.Telegram_BOT_TOKEN }}
      SLACK_BOT_TOKEN: ${{ vars.SLACK_BOT_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ vars.SLACK_SIGNING_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - name: check secret
        shell: bash
        run: echo "the environment is $TEST_DATABASE_URI"

      - name: Build the stack
        working-directory: fast_api_backend
        run: docker-compose up -d

      # add 10 second waiting time

      - name: wait for 10 seconds
        run: sleep 10

      - name: check docker-compose running
        working-directory: fast_api_backend
        run: docker-compose ps

      # print the database logs
      - name: check database logs
        working-directory: fast_api_backend
        run: docker-compose logs db

      - name: create a test db
        working-directory: fast_api_backend
        run: docker-compose exec -T db createdb -U root slack-bot-test

      # print the database logs2
      - name: check database logs2
        working-directory: fast_api_backend
        run: docker-compose logs db

      - name: Run tests
        working-directory: fast_api_backend
        run: docker-compose exec -T backend pytest -p no:warnings -s
